version: '3'

services:
  mumuseason2-api:
    container_name: mumuseason2-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app/
    networks:
      - mumuseason2-api
    depends_on:
      - mumuseason2-database
    #entrypoint: ./wait-for-it.sh mumuseason2-database:5432 

  mumuseason2-database:
    container_name: mumuseason2-database
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT= ${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      #- mumuseason2-msdata:/var/lib/mysql
      #- ./init:/docker-entrypoint-initdb.d
      - mumuseason2-msdata:/var/lib/mysql
    networks:
      - mumuseason2-api

  redis:
    container_name: mumuseason2-redis
    image: redis:5.0.3
    restart: always
    hostname: ${REDIS_HOST}
    network_mode: host
    ports:
        - "6379:6379"
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

    

networks:
  mumuseason2-api:
    driver: bridge

volumes:
  mumuseason2-msdata: